import matplotlib.pyplot as plt
import csv

times = []
costs = []

# 1. Read the CSV generated by the bash script
try:
    with open('cutoff_results.csv', 'r') as f:
        reader = csv.reader(f)
        next(reader) # Skip header
        for row in reader:
            if row:
                times.append(int(row[0]))
                costs.append(float(row[1]))
except FileNotFoundError:
    print("Error: cutoff_results.csv not found. Run the bash script first.")
    exit()

# 2. Create the Plot
plt.figure(figsize=(10, 6))
plt.plot(times, costs, marker='o', linestyle='-', color='b', label='Simulated Annealing')

# 3. Styling
plt.title('Effect of Cutoff Time on Solution Quality (Atlanta.tsp)')
plt.xlabel('Cutoff Time (seconds)')
plt.ylabel('Solution Quality (Total Distance)')
plt.grid(True, which='both', linestyle='--', linewidth=0.5)

# 4. Save
plt.savefig('cutoff_plot.png')
print("Plot saved as cutoff_plot.png")